version: '2.4'
services:
  workspace:
    image: busybox
    volumes:
      - ~/Documents/latex:/Documents/latex
      - ../thesis_settings.tex:/Documents/latex/thesis/thesis_settings.tex
      - .latexmkrc:/root/.latexmkrc
      - .textlintrc:/root/.textlintrc
      - ../lint:/usr/local/bin
  tex:
    build: .
    platform: linux/aarch64
    container_name: tex
    tty: true
    working_dir: /Documents/latex
    volumes_from:
      - workspace
